using System;
using System.Collections.Generic;
using System.Linq;

namespace UntappdViewer.Helpers
{
    public static class CountryNameHelper
    {
        private static readonly Dictionary<string, string> countryCodeByName = GetCountryCodeByName();

        public static Dictionary<string, T> ConvertNameToCode<T>(Dictionary<string, T> countries)
        {
            Dictionary<string, T> countryCodes = new Dictionary<string, T>();
            foreach (KeyValuePair<string, T> country in countries)
            {
                string code = countryCodeByName.FirstOrDefault(item => item.Value.ToLower().Equals(country.Key.ToLower())).Key;
                countryCodes.Add(String.IsNullOrEmpty(code) ? country.Key : code, country.Value);
            }
            return countryCodes;
        }

        private static Dictionary<string, string> GetCountryCodeByName()
        {
            Dictionary<string, string> countryCodeByName = new Dictionary<string, string>();
            countryCodeByName.Add("-99", "Fr. S. Antarctic Lands");
            countryCodeByName.Add("-991", "N. Cyprus");
            countryCodeByName.Add("-992", "Falkland Is.");
            countryCodeByName.Add("-993", "W. Sahara");
            countryCodeByName.Add("-994", "Somaliland");
            countryCodeByName.Add("-995", "Taiwan");
            countryCodeByName.Add("AE", "United Arab Emirates");
            countryCodeByName.Add("AF", "Afghanistan");
            countryCodeByName.Add("AL", "Albania");
            countryCodeByName.Add("AM", "Armenia");
            countryCodeByName.Add("AO", "Angola");
            countryCodeByName.Add("AR", "Argentina");
            countryCodeByName.Add("AT", "Austria");
            countryCodeByName.Add("AU", "Australia");
            countryCodeByName.Add("AZ", "Azerbaijan");
            countryCodeByName.Add("BA", "Bosnia and Herz.");
            countryCodeByName.Add("BD", "Bangladesh");
            countryCodeByName.Add("BE", "Belgium");
            countryCodeByName.Add("BF", "Burkina Faso");
            countryCodeByName.Add("BG", "Bulgaria");
            countryCodeByName.Add("BI", "Burundi");
            countryCodeByName.Add("BJ", "Benin");
            countryCodeByName.Add("BN", "Brunei");
            countryCodeByName.Add("BO", "Bolivia");
            countryCodeByName.Add("BR", "Brazil");
            countryCodeByName.Add("BS", "Bahamas");
            countryCodeByName.Add("BT", "Bhutan");
            countryCodeByName.Add("BW", "Botswana");
            countryCodeByName.Add("BY", "Belarus");
            countryCodeByName.Add("BZ", "Belize");
            countryCodeByName.Add("CA", "Canada");
            countryCodeByName.Add("CF", "Central African Rep.");
            countryCodeByName.Add("CG", "Congo");
            countryCodeByName.Add("CH", "Switzerland");
            countryCodeByName.Add("CI", "Ivory Coast");
            countryCodeByName.Add("CL", "Chile");
            countryCodeByName.Add("CM", "Cameroon");
            countryCodeByName.Add("CN", "China");
            countryCodeByName.Add("CO", "Colombia");
            countryCodeByName.Add("CR", "Costa Rica");
            countryCodeByName.Add("CU", "Cuba");
            countryCodeByName.Add("CY", "Cyprus");
            countryCodeByName.Add("CZ", "Czech Rep.");
            countryCodeByName.Add("DE", "Germany");
            countryCodeByName.Add("DJ", "Djibouti");
            countryCodeByName.Add("DK", "Denmark");
            countryCodeByName.Add("DO", "Dominican Rep.");
            countryCodeByName.Add("DZ", "Algeria");
            countryCodeByName.Add("EC", "Ecuador");
            countryCodeByName.Add("EE", "Estonia");
            countryCodeByName.Add("EG", "Egypt");
            countryCodeByName.Add("ER", "Eritrea");
            countryCodeByName.Add("ES", "Spain");
            countryCodeByName.Add("ET", "Ethiopia");
            countryCodeByName.Add("FI", "Finland");
            countryCodeByName.Add("FJ", "Fiji");
            countryCodeByName.Add("FR", "France");
            countryCodeByName.Add("GA", "Gabon");
            countryCodeByName.Add("GB", "United Kingdom");
            countryCodeByName.Add("GE", "Georgia");
            countryCodeByName.Add("GH", "Ghana");
            countryCodeByName.Add("GL", "Greenland");
            countryCodeByName.Add("GM", "Gambia");
            countryCodeByName.Add("GN", "Guinea");
            countryCodeByName.Add("GQ", "Eq. Guinea");
            countryCodeByName.Add("GR", "Greece");
            countryCodeByName.Add("GT", "Guatemala");
            countryCodeByName.Add("GW", "Guinea-Bissau");
            countryCodeByName.Add("GY", "Guyana");
            countryCodeByName.Add("GZ", "Palestine");
            countryCodeByName.Add("HN", "Honduras");
            countryCodeByName.Add("HR", "Croatia");
            countryCodeByName.Add("HT", "Haiti");
            countryCodeByName.Add("HU", "Hungary");
            countryCodeByName.Add("ID", "Indonesia");
            countryCodeByName.Add("IE", "Ireland");
            countryCodeByName.Add("IL", "Israel");
            countryCodeByName.Add("IN", "India");
            countryCodeByName.Add("IQ", "Iraq");
            countryCodeByName.Add("IR", "Iran");
            countryCodeByName.Add("IS", "Iceland");
            countryCodeByName.Add("IT", "Italy");
            countryCodeByName.Add("JM", "Jamaica");
            countryCodeByName.Add("JO", "Jordan");
            countryCodeByName.Add("JP", "Japan");
            countryCodeByName.Add("KE", "Kenya");
            countryCodeByName.Add("KG", "Kyrgyzstan");
            countryCodeByName.Add("KH", "Cambodia");
            countryCodeByName.Add("KP", "Dem. Rep. Korea");
            countryCodeByName.Add("KR", "Korea");
            countryCodeByName.Add("KV", "Kosovo");
            countryCodeByName.Add("KW", "Kuwait");
            countryCodeByName.Add("KZ", "Kazakhstan");
            countryCodeByName.Add("LA", "Lao PDR");
            countryCodeByName.Add("LB", "Lebanon");
            countryCodeByName.Add("LK", "Sri Lanka");
            countryCodeByName.Add("LR", "Liberia");
            countryCodeByName.Add("LS", "Lesotho");
            countryCodeByName.Add("LT", "Lithuania");
            countryCodeByName.Add("LU", "Luxembourg");
            countryCodeByName.Add("LV", "Latvia");
            countryCodeByName.Add("LY", "Libya");
            countryCodeByName.Add("MA", "Morocco");
            countryCodeByName.Add("MD", "Moldova");
            countryCodeByName.Add("ME", "Montenegro");
            countryCodeByName.Add("MG", "Madagascar");
            countryCodeByName.Add("MK", "Macedonia");
            countryCodeByName.Add("ML", "Mali");
            countryCodeByName.Add("MM", "Myanmar");
            countryCodeByName.Add("MN", "Mongolia");
            countryCodeByName.Add("MR", "Mauritania");
            countryCodeByName.Add("MW", "Malawi");
            countryCodeByName.Add("MX", "Mexico");
            countryCodeByName.Add("MY", "Malaysia");
            countryCodeByName.Add("MZ", "Mozambique");
            countryCodeByName.Add("NA", "Namibia");
            countryCodeByName.Add("NC", "New Caledonia");
            countryCodeByName.Add("NE", "Niger");
            countryCodeByName.Add("NG", "Nigeria");
            countryCodeByName.Add("NI", "Nicaragua");
            countryCodeByName.Add("NL", "Netherlands");
            countryCodeByName.Add("NO", "Norway");
            countryCodeByName.Add("NP", "Nepal");
            countryCodeByName.Add("NZ", "New Zealand");
            countryCodeByName.Add("OM", "Oman");
            countryCodeByName.Add("PA", "Panama");
            countryCodeByName.Add("PE", "Peru");
            countryCodeByName.Add("PG", "Papua New Guinea");
            countryCodeByName.Add("PH", "Philippines");
            countryCodeByName.Add("PK", "Pakistan");
            countryCodeByName.Add("PL", "Poland");
            countryCodeByName.Add("PR", "Puerto Rico");
            countryCodeByName.Add("PT", "Portugal");
            countryCodeByName.Add("PY", "Paraguay");
            countryCodeByName.Add("QA", "Qatar");
            countryCodeByName.Add("RO", "Romania");
            countryCodeByName.Add("RU", "Russia");
            countryCodeByName.Add("RW", "Rwanda");
            countryCodeByName.Add("RY", "Yemen");
            countryCodeByName.Add("SA", "Saudi Arabia");
            countryCodeByName.Add("SB", "Solomon Is.");
            countryCodeByName.Add("SD", "Sudan");
            countryCodeByName.Add("SE", "Sweden");
            countryCodeByName.Add("SI", "Slovenia");
            countryCodeByName.Add("SK", "Slovakia");
            countryCodeByName.Add("SL", "Sierra Leone");
            countryCodeByName.Add("SN", "Senegal");
            countryCodeByName.Add("SO", "Somalia");
            countryCodeByName.Add("SR", "Suriname");
            countryCodeByName.Add("SS", "S. Sudan");
            countryCodeByName.Add("SV", "El Salvador");
            countryCodeByName.Add("SY", "Syria");
            countryCodeByName.Add("SZ", "Swaziland");
            countryCodeByName.Add("TD", "Chad");
            countryCodeByName.Add("TG", "Togo");
            countryCodeByName.Add("TH", "Thailand");
            countryCodeByName.Add("TJ", "Tajikistan");
            countryCodeByName.Add("TM", "Turkmenistan");
            countryCodeByName.Add("TN", "Tunisia");
            countryCodeByName.Add("TP", "Timor-Leste");
            countryCodeByName.Add("TR", "Turkey");
            countryCodeByName.Add("TT", "Trinidad and Tobago");
            countryCodeByName.Add("TZ", "Tanzania");
            countryCodeByName.Add("UA", "Ukraine");
            countryCodeByName.Add("UG", "Uganda");
            countryCodeByName.Add("US", "United States");
            countryCodeByName.Add("UY", "Uruguay");
            countryCodeByName.Add("UZ", "Uzbekistan");
            countryCodeByName.Add("VE", "Venezuela");
            countryCodeByName.Add("VN", "Vietnam");
            countryCodeByName.Add("VU", "Vanuatu");
            countryCodeByName.Add("YF", "Serbia");
            countryCodeByName.Add("ZA", "South Africa");
            countryCodeByName.Add("ZM", "Zambia");
            countryCodeByName.Add("ZR", "Dem. Rep. Congo");
            countryCodeByName.Add("ZW", "Zimbabwe");
            return countryCodeByName;
        }
    }
}