//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UntappdViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UntappdViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream about_sound {
            get {
                return ResourceManager.GetStream("about_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABV.
        /// </summary>
        public static string ABV {
            get {
                return ResourceManager.GetString("ABV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UntappdViewer.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported File: {0}.
        /// </summary>
        public static string ArgumentExceptioSaveUntappdProject {
            get {
                return ResourceManager.GetString("ArgumentExceptioSaveUntappdProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application?.
        /// </summary>
        public static string AskCloseApp {
            get {
                return ResourceManager.GetString("AskCloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkins will be deleted. Continue?.
        /// </summary>
        public static string AskDeletedCheckins {
            get {
                return ResourceManager.GetString("AskDeletedCheckins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to save your changes untappd project?.
        /// </summary>
        public static string AskSaveСhangesUntappdProject {
            get {
                return ResourceManager.GetString("AskSaveСhangesUntappdProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average chekins quantity:.
        /// </summary>
        public static string AverageChekinsQuantity {
            get {
                return ResourceManager.GetString("AverageChekinsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average rating:.
        /// </summary>
        public static string AverageRating {
            get {
                return ResourceManager.GetString("AverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average unique chekins quantity:.
        /// </summary>
        public static string AverageUniqueChekinsQuantity {
            get {
                return ResourceManager.GetString("AverageUniqueChekinsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        public static string Badges {
            get {
                return ResourceManager.GetString("Badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer.
        /// </summary>
        public static string Beer {
            get {
                return ResourceManager.GetString("Beer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon beer_glass {
            get {
                object obj = ResourceManager.GetObject("beer_glass", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer Update.
        /// </summary>
        public static string BeerUpdate {
            get {
                return ResourceManager.GetString("BeerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bottle_3x {
            get {
                object obj = ResourceManager.GetObject("bottle_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breweries count Main/Collaboration:.
        /// </summary>
        public static string BreweriesCountMainCollaboration {
            get {
                return ResourceManager.GetString("BreweriesCountMainCollaboration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brewery.
        /// </summary>
        public static string Brewery {
            get {
                return ResourceManager.GetString("Brewery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap can_3x {
            get {
                object obj = ResourceManager.GetObject("can_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cask_3x {
            get {
                object obj = ResourceManager.GetObject("cask_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon chart_icon {
            get {
                object obj = ResourceManager.GetObject("chart_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkin.
        /// </summary>
        public static string Checkin {
            get {
                return ResourceManager.GetString("Checkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkins.
        /// </summary>
        public static string Checkins {
            get {
                return ResourceManager.GetString("Checkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkins count Total/Unique:.
        /// </summary>
        public static string CheckinsCountTotalUnique {
            get {
                return ResourceManager.GetString("CheckinsCountTotalUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkins Report.
        /// </summary>
        public static string CheckinsReport {
            get {
                return ResourceManager.GetString("CheckinsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chekin rating score.
        /// </summary>
        public static string ChekinRatingScore {
            get {
                return ResourceManager.GetString("ChekinRatingScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chekins Accumulate Count/Date.
        /// </summary>
        public static string ChekinsAccumulateCountDate {
            get {
                return ResourceManager.GetString("ChekinsAccumulateCountDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chekins Count/Date.
        /// </summary>
        public static string ChekinsCountDate {
            get {
                return ResourceManager.GetString("ChekinsCountDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaboration with.
        /// </summary>
        public static string CollaborationWith {
            get {
                return ResourceManager.GetString("CollaborationWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries count:.
        /// </summary>
        public static string CountriesCountLabel {
            get {
                return ResourceManager.GetString("CountriesCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country/Count.
        /// </summary>
        public static string CountryCount {
            get {
                return ResourceManager.GetString("CountryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country/Rating.
        /// </summary>
        public static string CountryRating {
            get {
                return ResourceManager.GetString("CountryRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap crowler {
            get {
                object obj = ResourceManager.GetObject("crowler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap default_avatar {
            get {
                object obj = ResourceManager.GetObject("default_avatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap description_icon {
            get {
                object obj = ResourceManager.GetObject("description_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Profile.
        /// </summary>
        public static string DeveloperProfile {
            get {
                return ResourceManager.GetString("DeveloperProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon download_media {
            get {
                object obj = ResourceManager.GetObject("download_media", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Media.
        /// </summary>
        public static string DownloadMedia {
            get {
                return ResourceManager.GetString("DownloadMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap draft_3x {
            get {
                object obj = ResourceManager.GetObject("draft_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap earth_planet {
            get {
                object obj = ResourceManager.GetObject("earth_planet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fvasilets@gmail.com.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap empty_1x1 {
            get {
                object obj = ResourceManager.GetObject("empty_1x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter access token.
        /// </summary>
        public static string EnterAccessToken {
            get {
                return ResourceManager.GetString("EnterAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon excel_report {
            get {
                object obj = ResourceManager.GetObject("excel_report", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap facebook_like_beer {
            get {
                object obj = ResourceManager.GetObject("facebook_like_beer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Collaboration.
        /// </summary>
        public static string FillCollaboration {
            get {
                return ResourceManager.GetString("FillCollaboration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Serving Type.
        /// </summary>
        public static string FillServingType {
            get {
                return ResourceManager.GetString("FillServingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon gallery {
            get {
                object obj = ResourceManager.GetObject("gallery", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Project.
        /// </summary>
        public static string GalleryProject {
            get {
                return ResourceManager.GetString("GalleryProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap green_checkmark {
            get {
                object obj = ResourceManager.GetObject("green_checkmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap growler {
            get {
                object obj = ResourceManager.GetObject("growler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpMenuItem {
            get {
                return ResourceManager.GetString("HelpMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBU.
        /// </summary>
        public static string IBU {
            get {
                return ResourceManager.GetString("IBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBU/ABV.
        /// </summary>
        public static string IBUToABV {
            get {
                return ResourceManager.GetString("IBUToABV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_location_24 {
            get {
                object obj = ResourceManager.GetObject("icons8_location_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is already launched!.
        /// </summary>
        public static string InstanceExistsMessage {
            get {
                return ResourceManager.GetString("InstanceExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path is empty.
        /// </summary>
        public static string IsEmptyFilePath {
            get {
                return ResourceManager.GetString("IsEmptyFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Is locked.
        /// </summary>
        public static string IsLockedFile {
            get {
                return ResourceManager.GetString("IsLockedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading from.
        /// </summary>
        public static string LoadingFrom {
            get {
                return ResourceManager.GetString("LoadingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap no_image_icon {
            get {
                object obj = ResourceManager.GetObject("no_image_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Name.
        /// </summary>
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format not supported.
        /// </summary>
        public static string NoSupportedFile {
            get {
                return ResourceManager.GetString("NoSupportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not exists.
        /// </summary>
        public static string NotExistsFile {
            get {
                return ResourceManager.GetString("NotExistsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap noun_pint_glass {
            get {
                object obj = ResourceManager.GetObject("noun_pint_glass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or drop file project/untappd data:.
        /// </summary>
        public static string OpenFileCaption {
            get {
                return ResourceManager.GetString("OpenFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pbu_320_white {
            get {
                object obj = ResourceManager.GetObject("pbu_320_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcs..
        /// </summary>
        public static string PCS {
            get {
                return ResourceManager.GetString("PCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectMenuItem {
            get {
                return ResourceManager.GetString("ProjectMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap red_x {
            get {
                object obj = ResourceManager.GetObject("red_x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename project.
        /// </summary>
        public static string RenameProject {
            get {
                return ResourceManager.GetString("RenameProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sad_face {
            get {
                object obj = ResourceManager.GetObject("sad_face", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon save_as {
            get {
                object obj = ResourceManager.GetObject("save_as", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon save1 {
            get {
                object obj = ResourceManager.GetObject("save1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As Zip.
        /// </summary>
        public static string SaveAsZip {
            get {
                return ResourceManager.GetString("SaveAsZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving Type/Count.
        /// </summary>
        public static string ServingTypeCount {
            get {
                return ResourceManager.GetString("ServingTypeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving Type/Rating.
        /// </summary>
        public static string ServingTypeRating {
            get {
                return ResourceManager.GetString("ServingTypeRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created by.
        /// </summary>
        public static string Signature1 {
            get {
                return ResourceManager.GetString("Signature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (с) 2022.
        /// </summary>
        public static string Signature2 {
            get {
                return ResourceManager.GetString("Signature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartPageMenuItem {
            get {
                return ResourceManager.GetString("StartPageMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics Report.
        /// </summary>
        public static string StatisticsReport {
            get {
                return ResourceManager.GetString("StatisticsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style/Count.
        /// </summary>
        public static string StyleCount {
            get {
                return ResourceManager.GetString("StyleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style/Rating.
        /// </summary>
        public static string StyleRating {
            get {
                return ResourceManager.GetString("StyleRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap taster_3x {
            get {
                object obj = ResourceManager.GetObject("taster_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To End.
        /// </summary>
        public static string ToEnd {
            get {
                return ResourceManager.GetString("ToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total days:.
        /// </summary>
        public static string TotalDays {
            get {
                return ResourceManager.GetString("TotalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string UniqueCheckBoxContent {
            get {
                return ResourceManager.GetString("UniqueCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap untappd_bottles {
            get {
                object obj = ResourceManager.GetObject("untappd_bottles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untappd page.
        /// </summary>
        public static string UntappdPage {
            get {
                return ResourceManager.GetString("UntappdPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter untappd user name..
        /// </summary>
        public static string UntappdUserNameCaption {
            get {
                return ResourceManager.GetString("UntappdUserNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon upload_photo {
            get {
                object obj = ResourceManager.GetObject("upload_photo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photo.
        /// </summary>
        public static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ut_connection_default {
            get {
                object obj = ResourceManager.GetObject("ut_connection_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning..
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project to UNTP.
        /// </summary>
        public static string WarningMessageSaveProjectToUNTP {
            get {
                return ResourceManager.GetString("WarningMessageSaveProjectToUNTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon web {
            get {
                object obj = ResourceManager.GetObject("web", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Download Project.
        /// </summary>
        public static string WebDownloadProject {
            get {
                return ResourceManager.GetString("WebDownloadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon zip_file_icon {
            get {
                object obj = ResourceManager.GetObject("zip_file_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left mouse button: moving.
        /// </summary>
        public static string ZoomBorderLeftMouseButtonUse {
            get {
                return ResourceManager.GetString("ZoomBorderLeftMouseButtonUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right mouse button: reset.
        /// </summary>
        public static string ZoomBorderRightMouseButtonUse {
            get {
                return ResourceManager.GetString("ZoomBorderRightMouseButtonUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scroll whell: zoom.
        /// </summary>
        public static string ZoomBorderScrollUse {
            get {
                return ResourceManager.GetString("ZoomBorderScrollUse", resourceCulture);
            }
        }
    }
}
